### ISSUE TITLE
Route53 provider

### ISSUE THREAD

**Issue by danlsgiga** [libdns/libdns#1]
Created this issue following the steps listed at [Implementing Providers](https://github.com/libdns/libdns/wiki/Implementing-providers)

**Comment by danlsgiga** [comment]
@mholt, I also have the `caddy-dns` module ready... what's the best way to have it added to the caddy-dns org?

**Comment by danlsgiga** [comment]
Went ahead and created https://github.com/danlsgiga/route53... can transfer ownership to the `caddy-dns` org whenever you want.

**Comment by mholt** [comment]
@danlsgiga Great! This is fantastic. I got you all set up with the repositories and gave you maintain privileges on them.

Thank you!!
