### ISSUE TITLE
DNS UPDATE provider

### ISSUE THREAD

**Issue by emersion** [libdns/libdns#106]
It would be nice to support [DNS UPDATE](https://www.rfc-editor.org/rfc/rfc2136).

**Comment by mholt** [comment]
Interesting, that's a very old spec and this is the first I've heard of it. Do you know where it's used and supported already?

**Comment by emersion** [comment]
It's supported by most authoritative DNS servers (BIND, Knot, etc). So if one self-hosts DNS (that's my use-case), there's a good chance it'll be the API to use.

**Comment by emersion** [comment]
Partial implementation available at https://github.com/emersion/libdns-dnsupdate

**Comment by mholt** [comment]
Ha, no way -- I was just about to say, "I don't have time to implement this right now, but it sounds useful! Want to take a stab at it?" :slightly_smiling_face:

**Comment by emersion** [comment]
I have completed the implementation, but I can't seem to open a PR. Do I need to manually copy-paste the files of my repo to a fresh libdns fork?

**Comment by mholt** [comment]
You don't have to actually make a PR, I just think it makes it easier to review.

In this case the implementation is _very_ simple and LGTM after a quick pass. Thanks for contributing this!

I'll make a repo and give you access, pronto.

**Comment by emersion** [comment]
Thanks!
