### ISSUE TITLE
Mail-In-A-Box provider

### ISSUE THREAD

**Issue by luv2code** [libdns/libdns#108]
I built the following projects so that I could create a wildcard cert for my [Mail-In-A-Box](https://mailinabox.email/) dns server.

| Repo                                    | Description                                                                    |
|-----------------------------------------|--------------------------------------------------------------------------------|
| https://github.com/luv2code/gomiabdns   | A go lib and cli client for interacting with miab endpoints                    |
| https://github.com/luv2code/libdns-miab | A lib dns provider that uses gomiabdns                                         |
| https://github.com/luv2code/miab        | A Caddy module that uses libdns-miab to insert acme records for DNS challenges |

Please review and let me know what changes you would want to see in order to make the libdns provider and caddy module official.

**Comment by mholt** [comment]
Sorry it took me a while to get to this.

I'll make a libdns/mailinabox repo and add you to it, as well as cadddy-dns/mailinabox.

Make sure, if you haven't already:

- Your go.mod module paths are correct for their new homes
- Your code is safe for concurrent use

Thanks for contributing!

Once you push to those repos, you can add your module to the Caddy website in the Account area.

**Comment by luv2code** [comment]
@mholt I've created the repos, and I'll test and finish them off this weekend. I'm a little uncertain about the "safe for concurrent use" part. I think it is; but I'm not doing anything special because no state is maintained - every call is a from-scratch rest call to the API.

Could let me know if my module is good? Or maybe give me a use case for concurrent use so I can reason about where to put the guards?

Here are the links to the new repos for convenience:
[caddy-dns mailinabox](https://github.com/caddy-dns/mailinabox)
[libdns mailinabox](https://github.com/libdns/mailinabox)

**Comment by mholt** [comment]
The concurrency issue is, aside from data races, mainly up to how the DNS provider works. Since I don't use Mail In A Box, I can't tell you whether it's safe for concurrent use by looking at the code.

But I think what you have is a great start! Maybe just wait and see if anyone opens issues to know what to improve on.

**Comment by luv2code** [comment]
> Maybe just wait and see if anyone opens issues to know what to improve on.

I like a good pragmatic approach :)
