### ISSUE TITLE
Provider: acmeproxy / httpreq

### ISSUE THREAD

**Issue by KalleDK** [libdns/libdns#111]
You get to decide what we should call it here.

lego calls it httpreq
acme.sh calls it acmeproxy

But I would like to make the provider :)

**Comment by KalleDK** [comment]
Don't know how to make a pull request when I forked from your template, but the repo is here

https://github.com/KalleDK/httpreq

**Comment by mholt** [comment]
Thanks -- what is the link to the provider itself? Like what should I even be searching for?

**Comment by KalleDK** [comment]
> Thanks -- what is the link to the provider itself? Like what should I even be searching for?

There is no specific provider, it's like RFC2136, an implementation can be found here https://github.com/mdbraber/acmeproxy

**Comment by KalleDK** [comment]
It's often used to either provide a DNS provider in an semi airgapped network, to add more fine-grained control of the real provider that might not have it or to combine providers if you use more than one

**Comment by KalleDK** [comment]
I myself use it as a way to limit CloudFlare apitoken. Such that a server only is ever allowed to create / delete the txt record for a single fqdn. And as a bonus, should the server ever be compromised, I only need to revoke a single token (not a CloudFlare token)

**Comment by mholt** [comment]
It looks like the only definition of it is the implementation by @mdbraber, so let's call it `acmeproxy`.

**Comment by KalleDK** [comment]
Okay, I'll rename it in the repo and ping you again when it's done.

**Comment by KalleDK** [comment]
@mholt also please give some feedback if I need to change more than the name, while I'm at it

**Comment by mholt** [comment]
I scanned the code (it is very simple) and don't see any glaring issues -- I'll create a repo for you at libdns and another one at caddy-dns. Make sure when you push to those repos you update the go.mod package path.
