### ISSUE TITLE
New Provider Bunny (bunny.net)

### ISSUE THREAD

**Issue by dennismuench** [libdns/libdns#114]
Hi there,

I need bunny.net DNS support for caddy and created a corresponding provider using the template, while basing tests and structure on the [hetzner](https://github.com/libdns/hetzner) package. Tests are OK.

I prepared a repository for [transport](https://github.com/rewilok/libdnsbunny/tree/transfer)

```

BUNNY_TEST_API_KEY="***" BUNNY_TEST_ZONE="***.com" go test ./... -v
=== RUN   Test_AppendRecords
--- PASS: Test_AppendRecords (7.43s)
=== RUN   Test_DeleteRecords
--- PASS: Test_DeleteRecords (4.00s)
=== RUN   Test_GetRecords
--- PASS: Test_GetRecords (3.85s)
=== RUN   Test_SetRecords
--- PASS: Test_SetRecords (7.96s)
PASS
ok      github.com/rewilok/libdnsbunny  23.510s
```

**Comment by mholt** [comment]
Thank you!
