### ISSUE TITLE
New Provider: do.de

### ISSUE THREAD

**Issue by d-k-bo** [libdns/libdns#122]
I am not sure how to implement it. do.de only offers an `https://www.do.de/api/letsencrypt` endpoint that allows creating and deleting TXT records. There is no public API to manipulate other records.

[API Documentation](https://web.archive.org/web/20210307015600/https://www.do.de/wiki/LetsEncrypt_-_Entwickler) (archived, but the API is still the same)

**Comment by mholt** [comment]
Thanks for the contribution!
