### ISSUE TITLE
New provider: Dynu

### ISSUE THREAD

**Issue by taviowong** [libdns/libdns#123]
Hello, I have built a [Dynu](http://www.dynu.com/en-US) libdns provider and corresponding caddy dns module for my own use and would like to publish it here.

The repos can be found at https://github.com/taviowong/libdns-dynu and https://github.com/taviowong/caddy-dns-dynu. I have successfully obtained an SSL cert using the DNS challenge in Caddy.

However, since I am not well-versed in DNS, I am not sure how to test the other DNS record types other than TXT record which is used for the DNS challenge.

Also, during testing, I found Caddy used the domain name rather than my Dynu subdomain as the zone, which caused the API to fail. To work around the problem, I added a parameter to pass in the subdomain to translate between libdns record format (relative to domain name) and Dynu record format (relative to subdomain) using the RelativeName and AbsoluteName functions. I don't know if this is hackish so please let me know if there is a better way of approaching the problem.

Thanks!

**Comment by mholt** [comment]
CertMagic looks up the SOA record to know what the zone is. If the subdomain is not already the zone then it needs its own SOA record (but then, it wouldn't be a "subdomain" anymore, by some definitions.)

Can you elaborate a little more, with an example and link to the relevant code? I'll try to review.

**Comment by taviowong** [comment]
For example, if I get a subdomain chris.dynu.com from Dynu, although I don't own the domain/subdomain, Dynu's API allows me to add a few DNS records (TXT is one of those allowed records) to my subdomain.

For the purpose of the DNS-01 challenge, I can add a TXT record for _acme-challenge.chris.dynu.com and obtain an SSL cert for chris.dynu.com. In this case, having an SOA record is not a necessary condition for passing the challenge.

Back to Caddy's case, it looks up the SOA record for my subdomain and determines that dynu.com is the zone. To obtain a cert for chris.dynu.com, it decides to add a TXT record with name "_acme-challenge.chris" to the zone dynu.com. However, unlike Caddy, Dynu's API works on my subdomain and I need to add "_acme-challenge" to my subdomain chris.dynu.com instead. If I use my Caddy module without additional processing, Dynu's API fails as I obviously do not have the right to add anything to dynu.com.

So, to work around the issue, I convert "_acme-challenge.chris" to "_acme-challenge" when receiving inputs from libdns and vice versa when sending output to libdns to cheat Caddy into thinking I am operating on the zone. This does not matter to Let's Encrypt anyway as looking up the TXT record for _acme-challenge.chris.dynu.com gives it the answer it wants. The workaround seems to work and I can get an SSL cert from Let's Encrypt using my modified module.

The relevant lines can be found at https://github.com/taviowong/libdns-dynu/blob/a4518e7ce3f916a7a5ad9db7966390de9cfec435/provider.go#L154 and https://github.com/taviowong/libdns-dynu/blob/a4518e7ce3f916a7a5ad9db7966390de9cfec435/provider.go#L60.

Given I am unable to add SOA records for my subdomain, is this workaround the best I can do in order to automate the DNS-01 challenge for Dynu?

**Comment by mholt** [comment]
Ah, I see. So they basically give you a subdomain but don't give you an SOA / zone. In that case, I think your workaround is fine (if it works!) because of the provider-specific quirk.

Yeah, zone lookups are purely for our convenience so the user doesn't have to specify a zone and domain separately (lame and error-prone UX, IMO, since the zone can be looked up).

Anyway, I think that's probably fine. :) Thanks for implementing it!

I will make repos for you to push to momentarily.

**Comment by mholt** [comment]
Ok, repos created and I've invited you to them.

Remember to update your package name in go.mod, and also I'd recommend unexporting `Init()` since it's supposed to be called implicitly it looks like.

Nice work! And thanks again for the contribution to the ecosystem!

**Comment by taviowong** [comment]
Thanks! Will update the code before pushing to the repos.

One last question: is it possible to access the hostname specified in Caddyfile from the module? If so, I may be able to do away with setting the domain again in the config as there's an API for getting the "root domain" from the hostname.

**Comment by mholt** [comment]
I don't think so (the Caddyfile disappears when the config is loaded, because it's converted to JSON). What your module gets is basically the input to the methods that are called.
