### ISSUE TITLE
[Question] Is it possible to standardise initialisation of providers

### ISSUE THREAD

**Issue by pavanbuzz** [libdns/libdns#129]
Each provider requires init values other than `APIToken`. For instance [luadns][luadns] requires `Email` & `APIKey`, In [r53's][r53] case it doesn't require anything. [easydns][easydns] requires `APIKey` & `APIToken`. [Porkbun][porkbun] requires `APIKey` & `APISecretKey`. 

I am wondering if it's possible to have a common way to initialise providers like lego offers `NewDNSProvider`? Then each provider can retrieve their required values from Environment variables and return an instance of the Provider back? 

[luadns]: https://github.com/libdns/luadns
[r53]: https://github.com/libdns/route53
[easydns]: https://github.com/libdns/easydns/blob/b1bd1f408d77f23c0127d4b3b0bbefde55734340/_example/main.go#L35
[porkbun]: https://github.com/libdns/porkbun/blob/6dda640b5aefc4692dadf90da3756818b6da2d92/provider.go#L18

**Comment by mholt** [comment]
No, there are issues with environment variables that make it unsuitable in some deployments and at scale (there's also literally issues complaining about this in Lego and it's one reason I made libdns). So going back to env vars would be a regression.
