### ISSUE TITLE
OpenStack designate DNS provider

### ISSUE THREAD

**Issue by wolfedale** [libdns/libdns#13]
I would like to try to wite dns provider for OpenStack Designate.

**Comment by obynio** [comment]
Hello, feel free to post here your work on the OpenStack DNS integration in libdns
We can then create a repository and give you access to it 👍

**Comment by wolfedale** [comment]
Hi, I think I'm close with the code. I hope I will create a PR soon :-)

**Comment by wolfedale** [comment]
I just created PR [https://github.com/libdns/libdns/pull/14]

**Comment by obynio** [comment]
@mholt

**Comment by mholt** [comment]
I barely had a chance to start a review, I will finish it soon!
