### ISSUE TITLE
New provider: Huawei Cloud DNS

### ISSUE THREAD

**Issue by devhaozi** [libdns/libdns#137]
Hello, we have completed the provider of Huawei Cloud DNS and applied to add it to libdns.

https://github.com/devhaozi/huaweicloud

**Comment by devhaozi** [comment]
Here is the screenshots from the test:

![20241018220852](https://github.com/user-attachments/assets/3010c831-6229-44a4-879c-7f22c2d958b0)
![20241018220816](https://github.com/user-attachments/assets/bd50055a-3ffa-41f1-9965-d78855ad1fcb)

**Comment by mholt** [comment]
Great, thank you! I've sent an email inviting you to push to the new repositories, including a caddy-dns repository for use with Caddy.
