### ISSUE TITLE
AutoDNS/InternetX provider

### ISSUE THREAD

**Issue by till** [libdns/libdns#139]
I am building a provider to add support for [AutoDNS](https://autodns.com). Will make a PR once I figure everything out. :)

**Comment by mholt** [comment]
Great, thank you! Let me know if you have any questions.

**Comment by till** [comment]
@mholt Do I have to PR the code here? Read the instructions, but wasn't sure.

Otherwise, I'll create a personal repo that you can look at.

**Comment by mholt** [comment]
A PR can be helpful so I have some review tools, but it's not required. If your code requires more in-depth review then I may request it since in-line comments will be easier.

**Comment by till** [comment]
@mholt made a PR: https://github.com/till/libdns-autodns/pull/1 LMK what you think

**Comment by till** [comment]
I have a demo account, so I'll extend the tests later to cover it completely and likely also add dependabot to it.

**Comment by mholt** [comment]
Thanks for the contribution! Repos created and invites sent. :smiley:
