### ISSUE TITLE
[general q] go version

### ISSUE THREAD

**Issue by till** [libdns/libdns#140]
Hey,

sorry for opening this issue, was wondering is the go 1.18 a hard requirement for the provider libs? Seems I used a package that's not available, but I didn't want to cause mayhem by bumping my requirement.

Till

**Comment by mholt** [comment]
I don't think it is. (Most libdns consumers are CertMagic/Caddy, which requires much newer Go than 1.18.)

Closing, but feel free to continue discussion if needed.
