### ISSUE TITLE
INWX Provider

### ISSUE THREAD

**Issue by matthiasng** [libdns/libdns#22]
https://www.inwx.de/

PR coming soon.

**Comment by aslmx** [comment]
Any news? :)

**Comment by matthiasng** [comment]
I was waiting on #12.
Less time and much work, but i think i can implement it till end of march ⏳

**Comment by sphr2k** [comment]
Any news on this? :)

**Comment by mholt** [comment]
Implemented in #93 by @ihmels -- https://github.com/libdns/inwx
