### ISSUE TITLE
Azure DNS Provider

### ISSUE THREAD

**Issue by kurokobo** [libdns/libdns#24]
Add new provider for [Azure DNS](https://azure.microsoft.com/en-us/services/dns/).

**Comment by kurokobo** [comment]
@mholt 
Thank you for your support.
I've pushed my codes in [libdns/azure](https://github.com/libdns/azure) and [caddy-dns/azure](https://github.com/caddy-dns/azure) as `v0.1.0`, and I've tested those new repos work well with Caddy running in my container :)

Is there anything I need to work on to add Azure provider to the [download page](https://caddyserver.com/download) and [module list](https://caddyserver.com/docs/modules/)?
If there is nothing in particular for me, this issue is fine to close.

**Comment by mholt** [comment]
Cool, looks great!

To add it to the download page, just log in to your Caddy account (sign up if you don't have one already) and then click Register Package and fill out the couple of fields.

**Comment by kurokobo** [comment]
Thank you, I have completed the registration of the package. It's all done 👍
