### ISSUE TITLE
Gandi provider

### ISSUE THREAD

**Issue by obynio** [libdns/libdns#3]
Created this issue following the steps listed at [Implementing Providers](https://github.com/libdns/libdns/wiki/Implementing-providers).

I can add support for [Gandi](https://www.gandi.net/). Here is my part https://github.com/obynio/gandi

Feel free to comment 👍

**Comment by obynio** [comment]
For the matter, I already support a [similar plugin](https://github.com/obynio/certbot-plugin-gandi) in Python for Certbot. The language may be different but the goal stays the same.

**Comment by obynio** [comment]
I plan to work on the `caddy-dns` module once this is merged. I can transfer ownership of https://github.com/obynio/libdns-gandi to the caddy-dns org whenever you want.

**Comment by mholt** [comment]
Awesome! I'll take a look soon. Did you find that the libdns package compatible enough with the Gandi API? I am trying to make sure what we have so far is compatible enough for future providers so we don't have to change it later.

**Comment by obynio** [comment]
Imo the libdns package interfaces are great, they are simple to understand and versatile enough to be compatible with most of the providers. However I had troubles to implement them due to the strange design choices of the Gandi API. You can view it as an "edge case" that makes it hard to link with the libdns interfaces. I detailed these issues in my README but I can provide more details here if it's not clear enough.

Moreover, the Gandi API does not provide any ID for its records so I did not used `libdns.Record.ID` anywhere in my code, but I don't think it's an issue.

**Comment by mholt** [comment]
Excellent, everything looks good! I _love_ that your implementation doesn't require any dependencies, that's awesome.

Thanks for your feedback. Quirks with provider APIs are expected, and I just wanted to ensure the interfaces could handle it gracefully, and I guess it does in this case, it's hard to work around that. Anyway, glad to hear that everything else is working :)

I've created libdns/gandi and caddy-dns/gandi repositories and given you access to them. Feel free to push at your convenience!

**Comment by obynio** [comment]
Hello @mholt 

How can we get this module to get listed [on the wiki](https://caddyserver.com/docs/modules/) and on [the download page](https://caddyserver.com/download) ?

**Comment by obynio** [comment]
Nevermind, I found it. You can claim your module by [creating an account](https://caddyserver.com/account/) on the website and it will automatically get listed.
