### ISSUE TITLE
TransIP provider

### ISSUE THREAD

**Issue by mdbraber** [libdns/libdns#4]
Hi Matt - happy to write an implementation for TransIP

**Comment by obynio** [comment]
@mdbraber in my humble opinion, I think the best would be to write your module for TransIP in a repository of your own before posting it here so Matt can review it. It should take a day or two, feel free to ask if you need help :slightly_smiling_face:

**Comment by mholt** [comment]
That'll work, [or a pull request](https://github.com/libdns/libdns/wiki/Implementing-providers) is even better so I can make comments in-line if necessary.

**Comment by mdbraber** [comment]
Yes, I'll write one in my own repository and submit a PR.

**Comment by mdbraber** [comment]
See https://github.com/libdns/libdns/pull/5 for initial PR

**Comment by mdbraber** [comment]
Done: https://github.com/libdns/transip - thanks for the support
