### ISSUE TITLE
deSEC.io provider

### ISSUE THREAD

**Issue by rugk** [libdns/libdns#43]
https://desec.io/ is awesome and has a pretty good featurefull REST api: https://desec.readthedocs.io/en/latest/dns/domains.html 

It would be great if you could support it.

Downstream: https://github.com/mholt/caddy-dynamicdns/issues/8

**Comment by kmei3560** [comment]
I'd like to take on this project if there is still interest in using this service `desec.io`

**Comment by pgrunm** [comment]
I'm also interested in this provider. Maybe I can help? :)

**Comment by mholt** [comment]
I don't use this service, so anyone is welcome to implement it!

**Comment by kmei3560** [comment]
Hi @pgrunm, I haven't started coding this one yet, so feel free to help if you like. I took a look at the REST API and just been thinking about how to implement.

**Comment by fabricionaweb** [comment]
Im using the desec but I have no clue how to program in go...

**Comment by mholt** [comment]
Great opportunity to learn Go :)

Alternatively, I can implement this for a sufficiently-tiered [sponsor](https://github.com/sponsors/mholt).

But this is a way more fun project for someone learning Go IMO!

**Comment by ethanjli** [comment]
I'd be happy to work on this, but it's on my back-burner - I agree that this project would be a fun way for someone to learn Go!

If it'd be helpful for anyone interested in prototyping a solution, https://github.com/nrdcg/desec is a Go library for accessing desec's API, and it's what go-acme uses in https://github.com/go-acme/lego/tree/master/providers/dns/desec . It's also possible to talk directly to the deSEC API using only `net/http` - https://github.com/StackExchange/dnscontrol does that in https://github.com/StackExchange/dnscontrol/tree/master/providers/desec

Since desec's RRset API takes updates to the entire list of records for an RRset rather than updates to individual records, I imagine we'll need to GET the RRset before each record append/set/delete operation, and so we'll have to serialize the operations (e.g. with a mutex) for concurrency safety. This appears to be what the https://github.com/libdns/powerdns provider does (e.g. in https://github.com/libdns/powerdns/blob/master/client.go#L49).

**Comment by znkr** [comment]
I want this too, so I started to work on it. I am doing this in my free time and that's limited, but I hope to have something to show by end of next week.

**Comment by mholt** [comment]
Awesome, thanks @znkr!

**Comment by znkr** [comment]
To give a quick update. I have a working provider that just needs some polishing before I can send it for review. Unfortunately, I got sick and it will take a little bit longer.

**Comment by rugk** [comment]
@znkr FYI draft PRs are possible on GitHub btw, so if people already wanna have a look they can while you're still polishing hehe.🙃

**Comment by znkr** [comment]
Good point, I'll create one once I find some time for it and before polishing. I'm quite busy with life right now (sick family now) but I'll try to get that done by the end of this week.

**Comment by rugk** [comment]
Yeah that's great to hear. Just don't want that the code gets most, if life gets in ones way.🤗

**Comment by mholt** [comment]
Done in #103

**Comment by znkr** [comment]
Thanks for the quick review, Matt. I just pushed the implementation to https://github.com/libdns/desec. I'll work on the Caddy module (https://github.com/caddy-dns/desec) next.

**Comment by znkr** [comment]
Just uploaded the Caddy module. I am running this on a very small server at home and it seems to work (after some bug fixing of the libdns provider).

**Comment by fabricionaweb** [comment]
I can help to test it here as well. I just need to build with xcaddy right?

**Comment by znkr** [comment]
> I can help to test it here as well.

Thank you :)

> I just need to build with xcaddy right?

That's right; you need `xcaddy build  --with github.com/caddy-dns/desec` to build it.

**Comment by fabricionaweb** [comment]
I tried with my Caddyfile using the acme_dns globally and also tls settings for domain (no changes in the error), and it did not worked :(

Maybe is because Im using wildcard?

```
ERROR	tls.obtain	could not get certificate from issuer	{"identifier": "*.fabricio.dev", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "[*.fabricio.dev] solving challenges: waiting for solver certmagic.solverWrapper to be ready: timed out waiting for record to fully propagate; verify DNS provider configuration is correct - last error: <nil> (order=https://acme-v02.api.letsencrypt.org/acme/order/[redacted]) (ca=https://acme-v02.api.letsencrypt.org/directory)"}
```

In my Caddyfile I have
```
*.fabricio.dev {
        tls {
                dns desec {
                        token [redacted]
                }
        }

```

Btw if you want, we can continue in an issue or somewhere else

**Comment by znkr** [comment]
> Btw if you want, we can continue in an issue or somewhere else

Yes, please file an issue in caddy-dns/desec. I'll take a look as soon as I can.

From a quick look: It would be helpful to have more logs.

**Comment by fabricionaweb** [comment]
Just a heads up the `_acme-challenge` is being created at desec. 

But thanks very much for the job, I really really apreciate it. 

I will see what I can do and open an issue there.
Sorry for the noise.
