### ISSUE TITLE
Linode Provider

### ISSUE THREAD

**Issue by FuzzyMistborn** [libdns/libdns#47]
Would love to have the Linode provider added: https://developers-linode.netlify.app/api/v4/

**Comment by yzguy** [comment]
I'll take a look/stab at this!

**Comment by bcrochet** [comment]
I had actually been working on this. Can be found here: https://github.com/bcrochet/linode

I'll be going through all of the correct process shortly.

**Comment by bcrochet** [comment]
https://github.com/libdns/libdns/pull/94

**Comment by mholt** [comment]
Thanks @bcrochet !
