### ISSUE TITLE
Validation of inputs?

### ISSUE THREAD

**Issue by prologic** [libdns/libdns#50]
Hi 👋

I've recently built a [CoreDNS](https://coredns.io/) library for [libdns](https://github.com/libdns) over at [libdns-coredns](https://git.mills.io/prologic/libdns-coredns).

For some background, CoreDNS has a backend plugin called [etcd](https://coredns.io/plugins/etcd/) that is capable of serving records and entire zones out of an etcd kv cluster. Turns out this is pretty generally useful (_and actually CoreDNS is widely used_).

So I built the library for it, and then built a Terraform Provider for it too over at [terraform-provider-coredns](https://git.mills.io/prologic/terraform-provider-coredns).

My question is actually two-fold:

- What validations should we as libdns implementers be adding implementations that conform to the libdns interface?

I don't see any examples of any validation happening in other implementations or any guidance on this. I _feel_ like there should be some because right now it's entirely possible to create rubbish records.

- Feedback! I'd love for some feedback from anyone on what I've built above so far.

Thanks!

**Comment by mholt** [comment]
I suppose it depends on what defines "rubbish records." I would probably start by writing test cases demonstrating examples of what is and isn't allowed, then make sure they pass. Does that make sense / answer your question?

**Comment by prologic** [comment]
No not quite, that's a typical response to a "How do I test for X" 😂 -- I'm more asking about what guidingprincipless does the libdns library and interface didcate for validating inputs? It seems like that's either a) none or b) implementation specific

Which I'm fine with 😀

It's more of an open ended question; Should we define some rules? Should we tighten up the interface? etc
Or more specifically could/should `libdns.Record` (_the struct_) have a `.Validate()` method that returns an `error` if the record is not valid?

**Comment by mholt** [comment]
> what guidingprincipless does the libdns library and interface didcate for validating inputs? It seems like that's either a) none or b) implementation specific

I think probably everything is implementation-specific, since there's no standards for provider APIs, right?

> Should we define some rules? Should we tighten up the interface? etc
Or more specifically could/should libdns.Record (the struct) have a .Validate() method that returns an error if the record is not valid?

What makes a record invalid, though? And how do we guarantee it's the same for all possible DNS providers/origins?

**Comment by prologic** [comment]
I thought DNS was the same no matter what the provider 😁

**Comment by mholt** [comment]
That is definitely not true.

And I'm actually talking about DNS _APIs_ since that's what libdns interfaces with, not DNS itself.

**Comment by prologic** [comment]
Ahh I see. Yeah maybe I wasn't clear, I was specifically talking about validating the fields of the Record struct, like Type, Name and Value.

**Comment by prologic** [comment]
I could be wrong but pretty sure those are defined in the relevant RFC(s)?

**Comment by mholt** [comment]
DNS is, but libdns isn't concerned with actual DNS: just APIs. It's not a DNS server. While DNS servers should enforce DNS semantics, libdns is just to shuttle API payloads back and forth using a simple API revolving around DNS, but it doesn't care about the actual data/payload.

**Comment by prologic** [comment]
Right. I see where we've got our wires cross... Let me try to explain. In my specific implementation I've basically adding KV pairs to a distributed key/value database (etcd). There is a defined structure for these records but there is no validation on any of the data. Make sense?

So hence my question 😉 But I'm happy to close this discussion as "implemtnation specific"; you are right.

**Comment by mholt** [comment]
Yeah, it definitely does seem specific to the implementation then. Thanks for the raising the question.
