### ISSUE TITLE
Any chance of adding additional interfaces?

### ISSUE THREAD

**Issue by anderspitman** [libdns/libdns#52]
I'm fiddling around with building a "frontend" for libdns (think rclone for DNS). It would be useful (maybe necessary) for the tool to be able to list all available zones for a given provider account. Is something like this within the scope of the project? If not, any suggestions for where to look next?

**Comment by mholt** [comment]
We could do that. It doesn't have to be something we add right away though. Do you have a proposed method signature? If so, go ahead and describe it and even implement it if you want to. Then people can still use it even if we don't define it in this package (for now).

**Comment by anderspitman** [comment]
@mholt my hacked together prototype looks something like this:

```
type ZonesGetter interface {
	GetZones(ctx context.Context) ([]Zone, error)
}

type Zone struct {
        Name string
}
```

That's pretty much all I need. That enables listing out the domains available, which can then be interrogated individually to manipulate records.

**Comment by anderspitman** [comment]
Also, I'm not sure "zones" is the right terminology here. Some APIs only return domains. My understanding is that is the more constrained term, so it might be more appropriate.

**Comment by mholt** [comment]
Hmm, I don't really understand the difference between "zones" and "domains" in that regard (as far as provider APIs go)...

And that looks pretty good, except for the sake of bikeshedding, how about `ZoneLister` instead, with the method name `ListZones`? :man_shrugging:

**Comment by anderspitman** [comment]
Ha, I bikeshedded that exact choice for a few minutes last night. I agree ListZones is better.

**Comment by anderspitman** [comment]
Awesome, thanks for implementing this @mholt @Xinayder!

**Comment by eryajf** [comment]
I'm working on https://github.com/eryajf/cloud_dns_exporter project。

I noticed that the method of adding ListZones was mentioned here, but now it seems to be gone. I personally think that libDNS can consider adding a relatively complete method for obtaining domain resources.

**Comment by mholt** [comment]
What do you mean it's gone exactly? https://pkg.go.dev/github.com/libdns/libdns#ZoneLister

**Comment by eryajf** [comment]
> What do you mean it's gone exactly? [pkg.go.dev/github.com/libdns/libdns#ZoneLister](https://pkg.go.dev/github.com/libdns/libdns#ZoneLister)

It's amazing, I don't know where I saw it yesterday, but I couldn't find it. I have indeed seen it now. Additionally, I would like to ask if it is possible to expand the fields of the Zone structure here, instead of just having one Name field.

**Comment by mholt** [comment]
Sure -- what do you have in mind? What are your requirements?
