### ISSUE TITLE
Handling records with multiple answers

### ISSUE THREAD

**Issue by jroyalty** [libdns/libdns#66]
How should provider implementations handle records with multiple answers?  In particular, how should `rec1` be mapped to `libdns.Record`s?

```
rec1.multiexample.com.   3600 IN A 1.1.1.1
rec1.multiexample.com.   3600 IN A 2.2.2.2
rec1.multiexample.com.   3600 IN A 3.3.3.3
```
I can envision a couple of solutions, but I'm wondering: What do (or should) consumers of the libdns API expect?  I wasn't 100% clear from reading the docs.

**Comment by mholt** [comment]
The libdns APIs use slices ([`[]Record`](https://pkg.go.dev/github.com/libdns/libdns#Record)), so for example, `GetRecords()` would return a slice of 3 `A` records in that case.

(Hopefully that answers the question. Closing the issue, but feel free to continue discussion, and we will reopen if needed.)
