### ISSUE TITLE
Explanation of 'zone' arguments and 'Name' in Record

### ISSUE THREAD

**Issue by mdbraber** [libdns/libdns#7]
I'm trying to understand better how `libdns` is supposed to work by using an example.

- What is supposed to be contained in the `zone` string in the methods? Can this be any of example.com, subdomain.example.com and foo.subdomain.example.com?
- What is the `Name` field in a Record? Is it supposed to have the fqdn or just the sub part for this zone (guessing that would make the most sense)

In practice: my provider (TransIP) only gives me the ability to change the zones for a domain in the form of example.com, so I will always need to know the "domainname" of any zone. But if libdns supplies subdomain.example.com as zone argument and wants to change the record with the name 'foo' I'll have to implement some subdomain mangling.

**Comment by mholt** [comment]
> What is supposed to be contained in the zone string in the methods? Can this be any of example.com, subdomain.example.com and foo.subdomain.example.com?

I'm not really an expert at this either, but I think this is up to the DNS provider and/or registrar. I think usually this is a registered domain. In any case, it's the zone in which the record operations should be applied.

> What is the Name field in a Record? Is it supposed to have the fqdn or just the sub part for this zone (guessing that would make the most sense)

Usually just the sub part. Again, I think the nuances here vary by record type and DNS provider (unfortunately).

> In practice: my provider (TransIP) only gives me the ability to change the zones for a domain in the form of example.com, so I will always need to know the "domainname" of any zone.

Yes, Cloudflare is like that too, I noticed. My initial drafts didn't take a zone argument but found out that this was necessary.

> But if libdns supplies subdomain.example.com as zone argument and wants to change the record with the name 'foo' I'll have to implement some subdomain mangling.

If your method gets called with the wrong zone as input, that's a bug in the caller's code, not yours. You should just be able to use the zone as it comes in.

Does that answer your questions?

**Comment by mdbraber** [comment]
> > What is supposed to be contained in the zone string in the methods? Can this be any of example.com, subdomain.example.com and foo.subdomain.example.com?
> 
> I'm not really an expert at this either, but I think this is up to the DNS provider and/or registrar. I think usually this is a registered domain. In any case, it's the zone in which the record operations should be applied.

I guess it should be clear for those using the interface what is to be expected right? Otherwise it could be the case that someone uses the arguments  "subdomain.example.com" with name "foo", while someone else might use "example.com" as the argument with "foo.subdomain". Or should we always make sure we are handling this right?

> > What is the Name field in a Record? Is it supposed to have the fqdn or just the sub part for this zone (guessing that would make the most sense)
> 
> Usually just the sub part. Again, I think the nuances here vary by record type and DNS provider (unfortunately).

They do vary as far as I can see, but isn't it so `libdns` is to be able to be expecting the same inputs whatever the provider?
> > But if libdns supplies subdomain.example.com as zone argument and wants to change the record with the name 'foo' I'll have to implement some subdomain mangling.
> 
> If your method gets called with the wrong zone as input, that's a bug in the caller's code, not yours. You should just be able to use the zone as it comes in.

I'm thinking that the caller's code should be able to throw the same things at it independent of the provider being implement. That's what would make for a truly universal approach, right? Otherwise they'll have to know about all the providers and change their code, while I see the point of `libdns` being that `libdns` will handle that logic.

**Comment by mholt** [comment]
I agree it would be nice if it was the same for all providers, but I just don't know how to do that. I also don't know how much of an issue it actually is. Usually, a domain zone is a registered domain. (I think.)

**Comment by miekg** [comment]
In DNS a 'zone' is the bit of the DNS tree you have control over (are authoritative for). A domain contains all zones under it. So I'm authoritative for `miek.nl`which is the zone I own, the `.nl` domain includes `miek.nl`, the `.nl` zone only consists of a few (mandatory) records and a whole slew of NS records to delegate bits.

For a resource record the naming is easier:

`www.miek.nl. IN 3600 A 127.0.0.1` in that order: `<domainname>` `<class>` `<ttl>` `<type>` `<rdata>`
because the domain name (or just name) ends in a dot it's fully qualified, if it isn't another domain (usually called 'origin') is added to it to make it fully qualified.

**Comment by mholt** [comment]
Thanks for the explanation @miekg - that is remarkably helpful!

When creating a resource record (i.e. `www` subdomain of `example.com` where `example.com` is the zone), I've noticed that most providers want only the `www` part in the Name field, and they append the zone to it.

Anyway, thanks; I think that clarifies the confusion, at least for me.
