### ISSUE TITLE
Permission to libdns/nicrudns

### ISSUE THREAD

**Issue by maetx777** [libdns/libdns#70]
Hi!
Some time ago I have contributed (https://github.com/libdns/libdns/pull/68) nic.ru DNS API, you have created repo https://github.com/libdns/nicrudns , but I ahve not permission for publish:
```
$ git push origin master
ERROR: Permission to libdns/nicrudns.git denied to maetx777.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Can u help me? What I am doing wrong?

**Comment by mholt** [comment]
You have already been invited to the repo, you just need to accept the invitation.

<img width="523" alt="Screen Shot 2022-05-13 at 10 49 26 PM" src="https://user-images.githubusercontent.com/1128849/168411148-faf15181-2d2d-4c9d-b13b-6a1a6e33b9ec.png">

I saw your other comments [here](https://github.com/libdns/libdns/pull/68#issuecomment-1124582656) and [here](https://github.com/libdns/nicrudns/issues/1). Sorry for the delay, but please be patient while I am sick with covid. I have been trying to rest a lot.
