### ISSUE TITLE
Netlify Provider

### ISSUE THREAD

**Issue by CL0Pinette** [libdns/libdns#72]
Hi, I've implemented libns for Netlify a few weeks ago : https://github.com/CL0Pinette/libdns-netlify. I still have to do the testing part so that it meets the requirements of libdns, but most of the work is already done. 

I will try to make a PR asap.

**Comment by mholt** [comment]
Great! Will be happy to review it.

**Comment by CL0Pinette** [comment]
I have pushed and tagged the libdns module and caddy-dns implementation. I also registered the package on caddy.
