### ISSUE TITLE
RFC2136 provider

### ISSUE THREAD

**Issue by KoHcoJlb** [libdns/libdns#75]
Hello, I'm implementing rfc2136 provider and I have a question regarding how TXT records should be handled in libdns.
By DNS specification TXT record can have multiple values, which in zone file are separated by spaces and quoted if they contain spaces themselves. How does this correlates with Record's Value field?

**Comment by mholt** [comment]
Awesome, thanks for working on that!

Good question. I think a literal representation would be best. In other words, don't interpret the value at all. Don't interpret it as multiple values, just have it as-is. At least, that's my opinion/preference...

Aside: Perhaps we could add a `Values()` method to `Record` that could do the parsing as a convenience and return `[]string` if it's a multi-value TXT record?

**Comment by KoHcoJlb** [comment]
By as-is do you mean leave it in zone file format?

In fact that's the way I started to implement it when I faced with this confusion which, though seems more logical to me, would require users to quote value if it contains whitespaces. Moreover library which I'm using always quotes value during serialization, which will be the case when querying records from the server.

So I wanted to know what current usage practice is and stick to it.

**Comment by mholt** [comment]
> By as-is do you mean leave it in zone file format?

Yeah, I think so. `libdns` is a pretty low-level library, not really intended to interpret/parse record values. But I'd be OK with helper methods if there is a common need for some of that. But I don't think the low-level methods `Add/Set/Delete/Update` should do parsing/interpretation.

Anyway, this is a first for this question for `libdns`, so I'm just spitting out my initial thoughts here. What if we give it a try and then see how it works? We can add a helper method if needed.

**Comment by KoHcoJlb** [comment]
Ok, so I will implement it this way and submit a PR.

**Comment by mholt** [comment]
Thanks! If it turns out too clunky, awkward, or unworkable, we can revise it. But let's start with it this way first and see.
