### ISSUE TITLE
DNSimple Provider

### ISSUE THREAD

**Issue by git001** [libdns/libdns#76]
I plan to add the https://github.com/dnsimple/dnsimple-go to libdns.

**Comment by mholt** [comment]
Hey Aleks @git001 -- still have plans to do this?

**Comment by git001** [comment]
Sorry not time this year, for that :sob:  
Should I close it and reopen when I have time for that?

**Comment by mholt** [comment]
No, it's fine. I just wanted to get an update :)

**Comment by monirz** [comment]
@mholt Since it is not implemented yet or no one seems to be actively working on it yet. I'll be working on implementing it.

**Comment by mholt** [comment]
Awesome!! Thank you so much @omarjatoi. I'm sure many people will find your contribution useful :)

**Comment by mholt** [comment]
Huh, that's weird. You definitely have maintainer permissions. Make sure you're pushing with a key/login associated with your GitHub account...

**Comment by mholt** [comment]
Hmmm... weird! Ok keep me posted if I need to do anything else.
