### ISSUE TITLE
Azure DNS provider

### ISSUE THREAD

**Issue by loganjohnlong** [libdns/libdns#8]
Created this issue following the steps listed at [Implementing Providers](https://github.com/libdns/libdns/wiki/Implementing-providers)

**Comment by mholt** [comment]
Awesome! Will look forward to reviewing the implementation!

**Comment by obynio** [comment]
Hello, feel free to post here your work on the DuckDNS integration in libdns
We can then create a repository and give you access to it 👍

**Comment by kurokobo** [comment]
@loganjohnlong 
Thank you for creating this Issue.

Just to confirm, is there any update about your project?

I mean, currently, I'm also creating a libdns provider for Azure DNS for my personal use and it's almost done ([here](https://github.com/kurokobo/libdns-azure) and [here](https://github.com/kurokobo/caddy-dns-azure)), therefore I'm considering that I should make my implementation open to the coddy community or not.

If you are ok, I will try to create a PR about my Azure DNS provider. Thanks in advance.

**Comment by loganjohnlong** [comment]
@kurokobo Go ahead and submit yours if you have working code. I haven't had a chance to work on this at all.

**Comment by kurokobo** [comment]
Thank you for the quick reply.
Then I will proceed the procedure with my code. Thank you.
