### ISSUE TITLE
Scaleway provider

### ISSUE THREAD

**Issue by dirien** [libdns/libdns#83]
Hi @mholt 

I created the Scaleway provider here -> https://github.com/dirien/scaleway and would like to donate to this organisation, so we can use it in Caddy-DNS 8https://github.com/caddy-dns)

Would like to create a provider for Civo too, so interessted to see how the transfer process is working.

**Comment by dirien** [comment]
Ok, I found the instructions -> https://github.com/libdns/libdns/wiki/Implementing-providers 

Will create an PR 😅

**Comment by dirien** [comment]
Created PR #84

**Comment by mholt** [comment]
Thanks! Reviewed.
