### ISSUE TITLE
Claiming nja.la

### ISSUE THREAD

**Issue by katzeprior** [libdns/libdns#88]
Claiming nja.la, going to add it here for caddy support for a friend who needs it :)

**Comment by mholt** [comment]
@katzeprior https://github.com/libdns/libdns/compare -- see GitHub docs: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by katzeprior** [comment]
@mholt I know how to do normal pr requests, is my repo correct?
![image](https://user-images.githubusercontent.com/87608942/194427044-66fc1c61-8918-4a1c-94ea-c92f480a4bd1.png)
Can't select my katzeprior/njalla repo here
![image](https://user-images.githubusercontent.com/87608942/194427145-ea537735-fa99-48dd-8a0b-7704d7a6bd5c.png)

**Comment by mholt** [comment]
You can make a PR to the template repo I guess. The point is just that I need a page where I can review the code.
