### ISSUE TITLE
DuckDNS provider

### ISSUE THREAD

**Issue by PopeRigby** [libdns/libdns#9]

**Comment by obynio** [comment]
Hello, feel free to post here your work on the DuckDNS integration in libdns
We can then create a repository and give you access to it 👍

**Comment by francislavoie** [comment]
I wrote an initial implementation here: https://github.com/francislavoie/duckdns, I haven't tested it yet. WIP.

FYI @mholt if you wanted to take a quick peek.

**Comment by francislavoie** [comment]
Alright, it's ready to go! Works for me:

```
$ xcaddy build --with github.com/francislavoie/caddy-duckdns
```

Caddyfile:
```
example.duckdns.org {
        tls {
                dns duckdns {env.DUCKDNS_API_TOKEN}
        }

        root * /usr/share/caddy
        file_server
}
```

**Comment by mholt** [comment]
Awesome!! Thanks Francis! This will help a lot of people.

I went ahead and made the repos for your duckdns code. (Make sure to update any import paths that use the francislavoie account to use the new libdns/caddy-dns orgs.)

I believe that closes this up.

**Comment by francislavoie** [comment]
Alright it's pushed

```
xcaddy build --with github.com/caddy-dns/duckdns
```
