### ISSUE TITLE
New provider: Total Uptime

### ISSUE THREAD

**Issue by kmei3560** [libdns/libdns#90]
Hello, I'd like to build an integration with one of our providers Total Uptime.
Thanks!

**Comment by kmei3560** [comment]
Hey just a styling question. This provider tracks domains and records by an ID code (which is included as part of the URI in some calls).

Normally when I run into something like this, I optimize to just 1 API call for the entire domain list and then store that result in a global struct. Then I use that global as a cache for each subsequent call that needs to lookup an ID.

Is this style acceptable? Otherwise any better ideas? Just trying to avoid repeated expensive calls.
Thank you

**Comment by mholt** [comment]
You can do that, I think. Just make sure the API contract is not violated, so that your provider will work as documented & expected. :) But yeah, performance improvements (correct, safe ones) are always welcome!
