### ISSUE TITLE
Infomaniak support

### ISSUE THREAD

**Issue by yodatak** [libdns/libdns#95]
Hi i use a lot infomaniak and i want to use libdns with caddy server

here the lego go-acme implemantation
https://github.com/go-acme/lego/tree/master/providers/dns/infomaniak

And the certbot in python implemantation
https://github.com/Infomaniak/certbot-dns-infomaniak

I can provides acces to my dns /and or API if its easy for you 

Thanks a lot to building a saffer web !

**Comment by mholt** [comment]
Neat, thanks for the issue! Anyone is welcome to implement this.

**Comment by pelicangris** [comment]
I would love to have support for infomaniak too!

**Comment by yayathewall** [comment]
Just saw this now and wanted to let you know that I have started to work on it as I need it myself as well
