### ISSUE TITLE
Claiming Hosttech.ch

### ISSUE THREAD

**Issue by MasterEvarior** [libdns/libdns#96]
I'd like to implement this for [Hosttech.ch](hosttech.ch). 

I've already started but there are a few things I'd like to ask.
Is there a requirement for which types of records the interface should at least work? The API from the provider doesn't provide a way to set just any records, just the following:

- AAAA
- A
- CNAME
- MX
- MS
- PTR
- TXT
- TLSA

SRV and DS are also possible but these don't seems to make sense to map to the `libdns.Record` interface.

[API documentation](https://api.ns1.hosttech.eu/api/documentation/)

**Comment by mholt** [comment]
> Is there a requirement for which types of records the interface should at least work? 

The most common ones are TXT, A, and AAAA. But nope, there's no requirement.

You can do the best you can to satisfy the libdns interfaces, and then clearly document any caveats for your provider.

**Comment by MasterEvarior** [comment]
TXT, A and AAAA should all definitely be possible. Will update when I made some more progress

**Comment by MasterEvarior** [comment]
So I made some progress, to the point where it is pretty much finished and I'm almost ready to create a PR. But before that there are some questions I still have:

1. For the `SetRecords` method the comments say : 
```
// SetRecords sets the records in the zone, either by updating existing records or creating new ones.
// It returns the updated records.
```
Does that mean it *only* returns the updated records and no newly created? Or should it return newly created records also?

4.  In regards to the partially and full-qualified domain names. 
If I understand that correctly I should accept values such as `sub`, which then gets changed to `sub.zone.com` for my provider. Also that if the provider lists something like `example.zone.com` it should return `example.`
Is this correct?

**Comment by mholt** [comment]
Good questions:

> Does that mean it only returns the updated records and no newly created? Or should it return newly created records also?

I should probably rephrase that to say "the affected records". Basically, when `SetRecords()` finishes successfully, the DNS zone should look like the records passed in, for those records. Returning the records is necessary so any provider-specific information like an ID (or maybe a default TTL or something) can be returned to the caller.

> If I understand that correctly I should accept values such as sub, which then gets changed to sub.zone.com for my provider. Also that if the provider lists something like example.zone.com it should return example.
> Is this correct?

The `libdns` interfaces all work with _relative_ names. So you should accept names like `sub` and return names like `sub`. That's the extent of the rules for `libdns`. Your provider's API may have other requirements. If they require a FQDN, for example, you can use these helper methods to convert: https://pkg.go.dev/github.com/libdns/libdns#AbsoluteName

So if your provider gives you `sub.example.com` when listing records for `example.com`, you'll need to return names like `sub` to the caller, converting back to relative.

But it's really provider-dependent. As long as you accept and return relative names.

**Comment by MasterEvarior** [comment]
So I've finished writing the implementation (with some help :)).
I've made the repository public [here](https://github.com/MasterEvarior/libdns-hosttech). I don't usually write Go so I would be greatful if you'd look over it.

I will also write a caddy module for it, so I can use it with caddy.

**Comment by MasterEvarior** [comment]
> Edit: Where are you seeing those docs for SetRecords? I'm not seeing those: https://pkg.go.dev/github.com/libdns/libdns#RecordSetter

They are in the template repository, see [here](https://github.com/libdns/template/blob/d721b80a02076924402b5806571f98edc4e816d5/provider.go#L37)

**Comment by mholt** [comment]
Oh, I see. Thanks. I'll try to update that when I have a chance.

Anyway, nice work -- if it works for you, it looks good to me. Stylistically, I may have made some different choices, but that's ultimately up to you as you will be maintaining it. Thank you for the contribution!

I'll make the repos and invite you to them now.
