### ISSUE TITLE
implemented the tencentcloud provider

### ISSUE THREAD

**Issue by rehiy** [libdns/libdns#97]
I have implemented DNSPod provider using Tencent Cloud's new API  (version 3). I hope it can be included officially

`rehiy/libdns-tencentcloud` is based on the new version of Tencentcloud api, uses secret Id and key as authentication methods, supports permission settings, and supports DNSPod international version.

`libdns/dnspod` is based on the old version of dnspod.cn api, uses token as the authentication method, does not support permission settings, and does not support DNSPod international version.

Repo: https://github.com/rehiy/libdns-tencentcloud

**Comment by mholt** [comment]
Cool, looks good to me.

I'll make the repos and add you to them. (Including a caddy-dns repo for a Caddy module.)

Thanks for contributing this!

Don't forget, before you push, update your go.mod's module path.

**Comment by rehiy** [comment]
OK, I will submit the code to the git repository later
