### ISSUE TITLE
Wiki contradicts godoc with regards to thread-safety

### ISSUE THREAD

**Issue by znkr** [libdns/libdns#99]
The Wiki [says]( https://github.com/libdns/libdns/wiki/Implementing-providers)

> Each exported method must be safe for concurrent use (i.e. thread-safe) in the sense that there must be no data races. Atomicity with regards to DNS records is up to each individual provider's API.

But the [godoc](https://pkg.go.dev/github.com/libdns/libdns) provides more details that contradict the wiki

> All interface implementations must be safe for concurrent/parallel use. For example, if AppendRecords() is called at the same time and two API requests are made to the provider at the same time, the result of both requests must be visible after they both complete; if the provider does not synchronize the writing of the zone file and one request overwrites the other, then the client implementation must take care to synchronize on behalf of the incompetent provider. This synchronization need not be global; for example: the scope of synchronization might only need to be within the same zone, allowing multiple requests at once as long as all of them are for different zones. (Exact logic depends on the provider.)

I think this contradicts, because the godoc text explains a much stronger requirement ("the results of both requests must be visible after they both complete") than the text in the wiki ("no data races"). BTW: I also think that the usage of the word provider in both instances is confusing, because it's used for the client implementation and the upstream provider.

I am assuming that the wiki is outdated and that the godoc is correct. I can send a pull request to update the text in the wiki, but I would like to confirm that's the right approach or if reorganising the information would be preferable. Maybe it can be split into requirements for a provider module to be accepted under the libdns umbrella and requirements on how the interfaces need to be implemented? I can give it a shot and add references in both places.

**Comment by mholt** [comment]
This is a good point. Yes, I think we strengthened requirements in the godoc more recently than the wiki.

By "provider" we mean the actual remote service. I can't see a use of the term "provider" in the quoted text that means the client implementation. (We use "client implementation" for that.)

But yeah, we should probably clear this up:

- Client implementations (`libdns` packages) must be thread-safe, i.e. safe for concurrent-use, i.e. no data races.
- Two simultaneous method calls must result in either an error or the expected outcome of each call to be applied successfully.

Maybe we can start with this, I'd love to hear your thoughts on it.

**Comment by znkr** [comment]
I think what got me confused is that the client is always called `Provider` in Go.

Anyway, your suggestion is sound and I am happy to send a PR with the change In the coming days, but I don't mind if someone else changes it.
